"""Internal, read-only owner portal prototype."""

from .service import (
    OFFICE_SCOPE,
    SUCRE_OFFICE_FIELD,
    SUCRE_OFFICE_VALUE,
    build_owner_portal_view,
    get_owner_portal_property_view,
    is_procasa_sucre_property,
    select_preview_property_code,
)
from .semantics import (
    canonical_region,
    operation_price,
    region_to_macrozone,
    resolve_property_operations,
)
from .schemas import (
    DemandForecastViewV1,
    MarketIndicatorV1,
    MarketIntelligenceSnapshotV1,
    OwnerPortalAccessV1,
    OwnerPortalActivityPointV1,
    OwnerPortalComparableCohortV1,
    OwnerPortalComparableExampleV1,
    OwnerPortalEngineV1Contract,
    OwnerPortalEventV1,
    OwnerPortalMarketContextV1,
    OwnerPortalPublicationV1,
    OwnerPortalPositioningV1,
    OwnerPortalProvenanceV1,
    OwnerPortalPropertyViewV1,
    OwnerPortalTimelineEventV1,
    PriceResponseSimulationV1,
)

__all__ = [
    "OFFICE_SCOPE",
    "SUCRE_OFFICE_FIELD",
    "SUCRE_OFFICE_VALUE",
    "build_owner_portal_view",
    "get_owner_portal_property_view",
    "is_procasa_sucre_property",
    "select_preview_property_code",
    "canonical_region",
    "operation_price",
    "region_to_macrozone",
    "resolve_property_operations",
    "OwnerPortalAccessV1",
    "OwnerPortalEventV1",
    "OwnerPortalEngineV1Contract",
    "OwnerPortalProvenanceV1",
    "OwnerPortalPropertyViewV1",
    "MarketIndicatorV1",
    "MarketIntelligenceSnapshotV1",
    "DemandForecastViewV1",
    "PriceResponseSimulationV1",
    "OwnerPortalActivityPointV1",
    "OwnerPortalTimelineEventV1",
    "OwnerPortalPublicationV1",
    "OwnerPortalComparableCohortV1",
    "OwnerPortalComparableExampleV1",
    "OwnerPortalMarketContextV1",
    "OwnerPortalPositioningV1",
]
